spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.225:3306/canteenmanagement?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
    cache: false
server:
  servlet:
    context-path: /
  port: 8080